# Generated by Django 5.1.7 on 2025-03-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
